import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/Provider/SessionProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
